In [6]:
#import pandas  as pd
from sklearn.model_selection import train_test_split

In [4]:
pip install pandas

Collecting pandas
  Using cached pandas-2.2.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.23.2 (from pandas)
  Using cached numpy-2.2.5-cp311-cp311-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.2.3-cp311-cp311-win_amd64.whl (11.6 MB)
Using cached numpy-2.2.5-cp311-cp311-win_amd64.whl (12.9 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.5 pandas-2.2.3 pytz-2025.2 tzdata-2025.2
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install scikit_learn

Collecting scikit_learn
  Using cached scikit_learn-1.6.1-cp311-cp311-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from scikit_learn) (2.2.5)
Collecting scipy>=1.6.0 (from scikit_learn)
  Using cached scipy-1.15.2-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit_learn)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit_learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.6.1-cp311-cp311-win_amd64.whl (11.1 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached scipy-1.15.2-cp311-cp311-win_amd64.whl (41.2 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit_learn
Successfully installed joblib-1.4.2 scikit_learn-1.6.1 scipy-1.15.2 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install pickle

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle

In [1]:
pip install numpy

Requirement already satisfied: numpy in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (2.2.5)
Note: you may need to restart the kernel to use updated packages.

In [2]:
!pip install tensorflow pandas numpy scikit-learn matplotlib tensorboard streamlit

Collecting tensorflow
  Downloading tensorflow-2.19.0-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Requirement already satisfied: pandas in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (2.2.5)
Requirement already satisfied: scikit-learn in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (1.6.1)
Collecting matplotlib
  Using cached matplotlib-3.10.1-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting tensorboard
  Downloading tensorboard-2.19.0-py3-none-any.whl.metadata (1.8 kB)
Collecting streamlit
  Using cached streamlit-1.45.0-py3-none-any.whl.metadata (8.9 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Using cached absl_py-2.2.2-py3-none-any.whl.metadata (2.6 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=24.3.25 (from tensorflow)
  Using cached flatbuffers-25.2.10-py2.py3-none-any.whl.metadata (875 bytes)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
Collecting google-pasta>=0.1.1 (from tensorflow)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt-einsum>=2.3.2 (from tensorflow)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from tensorflow) (25.0)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 (from tensorflow)
  Downloading protobuf-5.29.4-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Collecting requests<3,>=2.21.0 (from tensorflow)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: setuptools in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from tensorflow) (75.8.0)
Requirement already satisfied: six>=1.12.0 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Using cached termcolor-3.0.1-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from tensorflow) (4.13.2)
Collecting wrapt>=1.11.0 (from tensorflow)
  Downloading wrapt-1.17.2-cp311-cp311-win_amd64.whl.metadata (6.5 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Using cached grpcio-1.71.0-cp311-cp311-win_amd64.whl.metadata (4.0 kB)
Collecting keras>=3.5.0 (from tensorflow)
  Downloading keras-3.9.2-py3-none-any.whl.metadata (6.1 kB)
Collecting numpy
  Downloading numpy-2.1.3-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting h5py>=3.11.0 (from tensorflow)
  Using cached h5py-3.13.0-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
Collecting ml-dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.1-cp311-cp311-win_amd64.whl.metadata (22 kB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow)
  Using cached tensorflow_io_gcs_filesystem-0.31.0-cp311-cp311-win_amd64.whl.metadata (14 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.6.0 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from scikit-learn) (3.6.0)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.2-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.57.0-cp311-cp311-win_amd64.whl.metadata (104 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.8-cp311-cp311-win_amd64.whl.metadata (6.3 kB)
Collecting pillow>=8 (from matplotlib)
  Using cached pillow-11.2.1-cp311-cp311-win_amd64.whl.metadata (9.1 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Using cached pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Collecting markdown>=2.6.8 (from tensorboard)
  Using cached markdown-3.8-py3-none-any.whl.metadata (5.1 kB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard)
  Using cached werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
Collecting altair<6,>=4.0 (from streamlit)
  Using cached altair-5.5.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<6,>=4.0 (from streamlit)
  Using cached cachetools-5.5.2-py3-none-any.whl.metadata (5.4 kB)
Collecting click<9,>=7.0 (from streamlit)
  Using cached click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Collecting packaging (from tensorflow)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pyarrow>=7.0 (from streamlit)
  Using cached pyarrow-20.0.0-cp311-cp311-win_amd64.whl.metadata (3.4 kB)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Using cached tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Using cached watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Using cached GitPython-3.1.44-py3-none-any.whl.metadata (13 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Using cached pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from streamlit) (6.2)
Collecting jinja2 (from altair<6,>=4.0->streamlit)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jsonschema>=3.0 (from altair<6,>=4.0->streamlit)
  Using cached jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting narwhals>=1.14.2 (from altair<6,>=4.0->streamlit)
  Using cached narwhals-1.37.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: colorama in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting rich (from keras>=3.5.0->tensorflow)
  Downloading rich-14.0.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.5.0->tensorflow)
  Downloading namex-0.0.9-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.5.0->tensorflow)
  Downloading optree-0.15.0-cp311-cp311-win_amd64.whl.metadata (49 kB)
Collecting charset-normalizer<4,>=2 (from requests<3,>=2.21.0->tensorflow)
  Using cached charset_normalizer-3.4.1-cp311-cp311-win_amd64.whl.metadata (36 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.21.0->tensorflow)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3,>=2.21.0->tensorflow)
  Using cached urllib3-2.4.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2.21.0->tensorflow)
  Using cached certifi-2025.4.26-py3-none-any.whl.metadata (2.5 kB)
Collecting MarkupSafe>=2.1.1 (from werkzeug>=1.0.1->tensorboard)
  Using cached MarkupSafe-3.0.2-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)
  Using cached attrs-25.3.0-py3-none-any.whl.metadata (10 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)
  Using cached jsonschema_specifications-2025.4.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)
  Using cached referencing-0.36.2-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)
  Using cached rpds_py-0.24.0-cp311-cp311-win_amd64.whl.metadata (4.2 kB)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.5.0->tensorflow)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\darsh\onedrive\desktop\ds_dl\venv\lib\site-packages (from rich->keras>=3.5.0->tensorflow) (2.19.1)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow-2.19.0-cp311-cp311-win_amd64.whl (375.9 MB)
   ---------------------------------------- 0.0/375.9 MB ? eta -:--:--
   ---------------------------------------- 1.6/375.9 MB 8.3 MB/s eta 0:00:45
   ---------------------------------------- 2.6/375.9 MB 6.3 MB/s eta 0:01:00
   ---------------------------------------- 3.4/375.9 MB 5.6 MB/s eta 0:01:07
   ---------------------------------------- 4.2/375.9 MB 5.0 MB/s eta 0:01:14
    --------------------------------------- 5.0/375.9 MB 4.7 MB/s eta 0:01:19
    --------------------------------------- 5.8/375.9 MB 4.5 MB/s eta 0:01:22
    --------------------------------------- 6.6/375.9 MB 4.4 MB/s eta 0:01:24
    --------------------------------------- 7.3/375.9 MB 4.3 MB/s eta 0:01:26
    --------------------------------------- 7.9/375.9 MB 4.3 MB/s eta 0:01:27
    --------------------------------------- 8.9/375.9 MB 4.3 MB/s eta 0:01:27
   - -------------------------------------- 9.4/375.9 MB 4.1 MB/s eta 0:01:30
   - -------------------------------------- 10.2/375.9 MB 4.1 MB/s eta 0:01:31
   - -------------------------------------- 10.7/375.9 MB 4.0 MB/s eta 0:01:32
   - -------------------------------------- 11.3/375.9 MB 3.9 MB/s eta 0:01:33
   - -------------------------------------- 12.1/375.9 MB 3.9 MB/s eta 0:01:35
   - -------------------------------------- 12.6/375.9 MB 3.8 MB/s eta 0:01:36
   - -------------------------------------- 13.1/375.9 MB 3.8 MB/s eta 0:01:37
   - -------------------------------------- 13.9/375.9 MB 3.7 MB/s eta 0:01:38
   - -------------------------------------- 14.7/375.9 MB 3.7 MB/s eta 0:01:37
   - -------------------------------------- 15.7/375.9 MB 3.8 MB/s eta 0:01:35
   - -------------------------------------- 16.5/375.9 MB 3.9 MB/s eta 0:01:33
   - -------------------------------------- 17.6/375.9 MB 3.8 MB/s eta 0:01:34
   - -------------------------------------- 18.4/375.9 MB 3.8 MB/s eta 0:01:33
   -- ------------------------------------- 19.1/375.9 MB 3.8 MB/s eta 0:01:33
   -- ------------------------------------- 19.9/375.9 MB 3.8 MB/s eta 0:01:34
   -- ------------------------------------- 20.4/375.9 MB 3.8 MB/s eta 0:01:34
   -- ------------------------------------- 21.2/375.9 MB 3.8 MB/s eta 0:01:34
   -- ------------------------------------- 22.0/375.9 MB 3.8 MB/s eta 0:01:34
   -- ------------------------------------- 23.1/375.9 MB 3.8 MB/s eta 0:01:33
   -- ------------------------------------- 23.6/375.9 MB 3.8 MB/s eta 0:01:33
   -- ------------------------------------- 24.4/375.9 MB 3.8 MB/s eta 0:01:33
   -- ------------------------------------- 25.2/375.9 MB 3.8 MB/s eta 0:01:33
   -- ------------------------------------- 25.7/375.9 MB 3.8 MB/s eta 0:01:34
   -- ------------------------------------- 26.5/375.9 MB 3.7 MB/s eta 0:01:34
   -- ------------------------------------- 27.0/375.9 MB 3.7 MB/s eta 0:01:34
   -- ------------------------------------- 27.8/375.9 MB 3.7 MB/s eta 0:01:34
   --- ------------------------------------ 28.6/375.9 MB 3.7 MB/s eta 0:01:34
   --- ------------------------------------ 29.1/375.9 MB 3.7 MB/s eta 0:01:35
   --- ------------------------------------ 30.1/375.9 MB 3.7 MB/s eta 0:01:34
   --- ------------------------------------ 30.9/375.9 MB 3.7 MB/s eta 0:01:33
   --- ------------------------------------ 31.7/375.9 MB 3.7 MB/s eta 0:01:33
   --- ------------------------------------ 32.2/375.9 MB 3.7 MB/s eta 0:01:33
   --- ------------------------------------ 32.8/375.9 MB 3.7 MB/s eta 0:01:33
   --- ------------------------------------ 33.6/375.9 MB 3.7 MB/s eta 0:01:34
   --- ------------------------------------ 34.3/375.9 MB 3.7 MB/s eta 0:01:34
   --- ------------------------------------ 34.9/375.9 MB 3.7 MB/s eta 0:01:34
   --- ------------------------------------ 35.7/375.9 MB 3.7 MB/s eta 0:01:33
   --- ------------------------------------ 36.7/375.9 MB 3.7 MB/s eta 0:01:32
   --- ------------------------------------ 37.5/375.9 MB 3.7 MB/s eta 0:01:32
   ---- ----------------------------------- 38.3/375.9 MB 3.7 MB/s eta 0:01:32
   ---- ----------------------------------- 38.8/375.9 MB 3.7 MB/s eta 0:01:32
   ---- ----------------------------------- 39.3/375.9 MB 3.7 MB/s eta 0:01:32
   ---- ----------------------------------- 40.1/375.9 MB 3.6 MB/s eta 0:01:33
   ---- ----------------------------------- 40.6/375.9 MB 3.6 MB/s eta 0:01:33
   ---- ----------------------------------- 41.2/375.9 MB 3.6 MB/s eta 0:01:33
   ---- ----------------------------------- 41.4/375.9 MB 3.6 MB/s eta 0:01:33
   ---- ----------------------------------- 41.9/375.9 MB 3.6 MB/s eta 0:01:35
   ---- ----------------------------------- 43.0/375.9 MB 3.6 MB/s eta 0:01:34
   ---- ----------------------------------- 44.3/375.9 MB 3.6 MB/s eta 0:01:32
   ---- ----------------------------------- 45.4/375.9 MB 3.7 MB/s eta 0:01:31
   ---- ----------------------------------- 46.1/375.9 MB 3.7 MB/s eta 0:01:31
   ---- ----------------------------------- 46.9/375.9 MB 3.6 MB/s eta 0:01:31
   ----- ---------------------------------- 47.4/375.9 MB 3.6 MB/s eta 0:01:31
   ----- ---------------------------------- 48.2/375.9 MB 3.6 MB/s eta 0:01:30
   ----- ---------------------------------- 49.0/375.9 MB 3.6 MB/s eta 0:01:30
   ----- ---------------------------------- 49.5/375.9 MB 3.6 MB/s eta 0:01:30
   ----- ---------------------------------- 50.6/375.9 MB 3.6 MB/s eta 0:01:30
   ----- ---------------------------------- 51.6/375.9 MB 3.7 MB/s eta 0:01:29
   ----- ---------------------------------- 52.2/375.9 MB 3.6 MB/s eta 0:01:29
   ----- ---------------------------------- 53.0/375.9 MB 3.6 MB/s eta 0:01:29
   ----- ---------------------------------- 53.7/375.9 MB 3.6 MB/s eta 0:01:29
   ----- ---------------------------------- 54.3/375.9 MB 3.6 MB/s eta 0:01:29
   ----- ---------------------------------- 55.1/375.9 MB 3.6 MB/s eta 0:01:29
   ----- ---------------------------------- 55.8/375.9 MB 3.6 MB/s eta 0:01:29
   ----- ---------------------------------- 56.4/375.9 MB 3.6 MB/s eta 0:01:29
   ------ --------------------------------- 57.4/375.9 MB 3.6 MB/s eta 0:01:28
   ------ --------------------------------- 58.2/375.9 MB 3.6 MB/s eta 0:01:28
   ------ --------------------------------- 59.0/375.9 MB 3.6 MB/s eta 0:01:28
   ------ --------------------------------- 59.8/375.9 MB 3.6 MB/s eta 0:01:27
   ------ --------------------------------- 60.3/375.9 MB 3.6 MB/s eta 0:01:27
   ------ --------------------------------- 61.1/375.9 MB 3.6 MB/s eta 0:01:27
   ------ --------------------------------- 61.9/375.9 MB 3.6 MB/s eta 0:01:27
   ------ --------------------------------- 62.4/375.9 MB 3.6 MB/s eta 0:01:27
   ------ --------------------------------- 63.2/375.9 MB 3.6 MB/s eta 0:01:27
   ------ --------------------------------- 64.0/375.9 MB 3.6 MB/s eta 0:01:27
   ------ --------------------------------- 64.7/375.9 MB 3.6 MB/s eta 0:01:26
   ------ --------------------------------- 65.5/375.9 MB 3.6 MB/s eta 0:01:26
   ------- -------------------------------- 66.1/375.9 MB 3.6 MB/s eta 0:01:26
   ------- -------------------------------- 66.8/375.9 MB 3.6 MB/s eta 0:01:26
   ------- -------------------------------- 67.4/375.9 MB 3.6 MB/s eta 0:01:26
   ------- -------------------------------- 68.2/375.9 MB 3.6 MB/s eta 0:01:26
   ------- -------------------------------- 68.9/375.9 MB 3.6 MB/s eta 0:01:25
   ------- -------------------------------- 69.7/375.9 MB 3.6 MB/s eta 0:01:25
   ------- -------------------------------- 70.5/375.9 MB 3.6 MB/s eta 0:01:25
   ------- -------------------------------- 71.3/375.9 MB 3.6 MB/s eta 0:01:25
   ------- -------------------------------- 72.1/375.9 MB 3.6 MB/s eta 0:01:24
   ------- -------------------------------- 72.9/375.9 MB 3.6 MB/s eta 0:01:24
   ------- -------------------------------- 73.4/375.9 MB 3.6 MB/s eta 0:01:24
   ------- -------------------------------- 74.2/375.9 MB 3.6 MB/s eta 0:01:24
   ------- -------------------------------- 75.0/375.9 MB 3.6 MB/s eta 0:01:24
   -------- ------------------------------- 75.8/375.9 MB 3.6 MB/s eta 0:01:24
   -------- ------------------------------- 76.5/375.9 MB 3.6 MB/s eta 0:01:23
   -------- ------------------------------- 77.3/375.9 MB 3.6 MB/s eta 0:01:23
   -------- ------------------------------- 78.1/375.9 MB 3.6 MB/s eta 0:01:23
   -------- ------------------------------- 78.9/375.9 MB 3.6 MB/s eta 0:01:23
   -------- ------------------------------- 79.7/375.9 MB 3.6 MB/s eta 0:01:22
   -------- ------------------------------- 80.2/375.9 MB 3.6 MB/s eta 0:01:22
   -------- ------------------------------- 80.7/375.9 MB 3.6 MB/s eta 0:01:22
   -------- ------------------------------- 81.3/375.9 MB 3.6 MB/s eta 0:01:22
   -------- ------------------------------- 81.8/375.9 MB 3.6 MB/s eta 0:01:23
   -------- ------------------------------- 82.3/375.9 MB 3.6 MB/s eta 0:01:23
   -------- ------------------------------- 82.8/375.9 MB 3.6 MB/s eta 0:01:23
   -------- ------------------------------- 83.4/375.9 MB 3.6 MB/s eta 0:01:23
   -------- ------------------------------- 83.9/375.9 MB 3.6 MB/s eta 0:01:23
   --------- ------------------------------ 84.7/375.9 MB 3.6 MB/s eta 0:01:22
   --------- ------------------------------ 86.0/375.9 MB 3.6 MB/s eta 0:01:22
   --------- ------------------------------ 87.3/375.9 MB 3.6 MB/s eta 0:01:21
   --------- ------------------------------ 88.1/375.9 MB 3.6 MB/s eta 0:01:20
   --------- ------------------------------ 88.9/375.9 MB 3.6 MB/s eta 0:01:20
   --------- ------------------------------ 89.4/375.9 MB 3.6 MB/s eta 0:01:20
   --------- ------------------------------ 90.2/375.9 MB 3.6 MB/s eta 0:01:20
   --------- ------------------------------ 91.0/375.9 MB 3.6 MB/s eta 0:01:20
   --------- ------------------------------ 91.5/375.9 MB 3.6 MB/s eta 0:01:20
   --------- ------------------------------ 92.3/375.9 MB 3.6 MB/s eta 0:01:19
   --------- ------------------------------ 93.1/375.9 MB 3.6 MB/s eta 0:01:19
   ---------- ----------------------------- 94.1/375.9 MB 3.6 MB/s eta 0:01:19
   ---------- ----------------------------- 94.6/375.9 MB 3.6 MB/s eta 0:01:18
   ---------- ----------------------------- 95.7/375.9 MB 3.6 MB/s eta 0:01:18
   ---------- ----------------------------- 96.2/375.9 MB 3.6 MB/s eta 0:01:18

In [36]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import pickle

In [37]:
data=pd.read_csv("Churn_Modelling.csv")

In [38]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [39]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [40]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [41]:
label_encoder_gender=LabelEncoder()
data["Gender"]=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [42]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [43]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [44]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [45]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [46]:
geo_endoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [47]:
geo_endoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [48]:
data=pd.concat([data.drop('Geography',axis=1),geo_endoded_df],axis=1)

In [49]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [ ]:
#save the encoders and scalar+2
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [52]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [53]:
X=data.drop('Exited',axis=1)
y=data['Exited']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

scaler= StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [57]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [58]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [61]:
#ANN Implementation
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime